"""empty message

Revision ID: 0b5c08b83d38
Revises: 91a7d9e5982e
Create Date: 2026-08-30 17:50:53.954752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5c08b83d38'
down_revision = '91a7d9e5982e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemons', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
