"""empty message

Revision ID: 1c01ad1451f0
Revises: 0b5c08b83d38
Create Date: 2026-09-19 19:21:12.455643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c01ad1451f0'
down_revision = '0b5c08b83d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'value', name='uq_filter_category_value')
    )
    with op.batch_alter_table('filter_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filter_options_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filter_options_category'))

    op.drop_table('filter_options')
    # ### end Alembic commands ###
